### ISSUE TITLE
et: lexical query produced no result

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-games#14]
double click on 'et' in Perseus.text.1999.02.0066/book1_poem1.html  (et nullo vivere consilio), I get lexical query produced no result.
one line below there is an other et with morphology populated
for the blank diagram and the inflection icon for 'et', see alpheios-project/components/issues/248

**Comment by balmas** [comment]
same problem as for #9 - mistake in the data-alpheios_tb_ref attribute. Fixed in the master branch of the texts repo. Need to push to the server still.

**Comment by monzug** [comment]
I thought so. if there is a better way to report them rather than GitHub
pls let me know

**Comment by balmas** [comment]
github is perfect. They are easy to keep track of here.

**Comment by monzug** [comment]
verified.
